version: "3"
services:
  wirecloud:
    image: ${IMAGE_WIRECLOUD}
    depends_on:
      - postgres
      - elasticsearch
      - memcached
    environment:
      - DEBUG=Ture
      - DB_HOST=postgres
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - FORWARDED_ALLOW_IPS=*
      - ELASTICSEARCH2_URL=http://elasticsearch:9200/
      - MEMCACHED_LOCATION=memcached:11211
      - FIWARE_IDM_SERVER=${IDM_HOST}
      - SOCIAL_AUTH_FIWARE_KEY=${WIRECLOUD_CLIENT_ID}
      - SOCIAL_AUTH_FIWARE_SECRET=${WIRECLOUD_CLIENT_SECRET}
    volumes:
      - ./data/wirecloud/wirecloud-data:/opt/wirecloud_instance/data
      - ./data/wirecloud/wirecloud-static:/var/www/static
    restart: always
    logging:
      driver: syslog
      options:
        tag: "[wirecloud]"

  elasticsearch:
    image: ${IMAGE_ELASTICSEARCH}
    volumes:
      - ./data/wirecloud/elasticsearch-data:/usr/share/elasticsearch/data
    command: elasticsearch -Des.index.max_result_window=50000
    restart: always
    logging:
      driver: syslog
      options:
        tag: "[elasticsearch]"

  memcached:
    image: ${IMAGE_MEMCACHED}
    command: memcached -m 2048m
    restart: always
    logging:
      driver: syslog
      options:
        tag: "[memcached]"

  ngsiproxy:
    image: ${IMAGE_NGSIPROXY}
    environment:
      - TRUST_PROXY_HEADERS=1
    restart: always
    logging:
      driver: syslog
      options:
        tag: "[ngsiproxy]"
