on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

jobs:
   create-release-tag:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TZ: 'Asia/Tokyo'
    steps:
      - run: echo ${{ github.ref }}
      - if: startsWith( github.ref, 'refs/tags/v' )
        env:
          REF: ${{ github.ref }}
        run: |
          echo "${REF##*/}" && \
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{ \"tag_name\": \"${REF##*/}\", \"name\": \"TEST ${REF##*/}\", \"body\": \"# Test\"}" \
            https://api.github.com/repos/${{ github.repository }}/releases
