name: Ubuntu latest
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-test:
    name: setup test

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install
      run: ./tests/script/coverage.sh

    - name: Run codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: coverage
